import { useEffect, useState } from "react"
import { useParams } from "react-router-dom"
import * as Tabs from "@radix-ui/react-tabs"
import { Plus, RefreshCw, CheckCircle, AlertTriangle, XCircle, Activity } from "lucide-react"
import { salesApi, productsApi, customersApi } from "@/api/system"
import { Card } from "@/components/ui/Card"
import { Button } from "@/components/ui/Button"
import { Badge } from "@/components/ui/Badge"
import { StatCard } from "@/components/ui/StatCard"
import { SlideOver } from "@/components/ui/SlideOver"
import { Input } from "@/components/ui/Input"
import { Select } from "@/components/ui/Select"
import { LineChart } from "@/components/charts"
import { useAppStore } from "@/stores/appStore"
import { PageSkeleton } from "@/components/ui/PageSkeleton"
